spring:
  application:
    name: payment-service

server:
  port: 8081

aws:
  dynamodb:
    table-name: ORDER

  sns:
    order-topic-arn: arn:aws:sns:us-east-1:200849340204:order-events

  sqs:
    payment-queue: payment-queue

